### ISSUE TITLE
Error in running copytransformer inference

### ISSUE THREAD

**Issue by andysu2008** [Alex-Fabbri/Multi-News#14]
Hello

I am trying to run your copy transformer baseline, in the `OpenNMT-py-baselines`, I loaded your pretrained checkpoint `newser_step_20000.pt `, then I run `./run_test_transformer.sh`

I received the following error:

  var = torch.tensor(arr, dtype=self.dtype, device=device)
```
Traceback (most recent call last):
  File "translate.py", line 37, in <module>
    main(opt)
  File "translate.py", line 24, in main
    attn_debug=opt.attn_debug)
  File "/Users/USER/Desktop/new_version_multi_news/Multi-News/code/OpenNMT-py-baselines/onmt/translate/translator.py", line 226, in translate
    batch_data = self.translate_batch(batch, data, fast=self.fast)
  File "/Users/USER/Desktop/new_version_multi_news/Multi-News/code/OpenNMT-py-baselines/onmt/translate/translator.py", line 329, in translate_batch
    return self._translate_batch(batch, data)
  File "/Users/USER/Desktop/new_version_multi_news/Multi-News/code/OpenNMT-py-baselines/onmt/translate/translator.py", line 555, in _translate_batch
    enc_states, memory_bank = self.model.encoder(src, src_lengths)
  File "/Users/USER/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/Users/USER/Desktop/new_version_multi_news/Multi-News/code/OpenNMT-py-baselines/onmt/encoders/transformer.py", line 102, in forward
    emb = self.embeddings(src)
  File "/Users/USER/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/Users/USER/Desktop/new_version_multi_news/Multi-News/code/OpenNMT-py-baselines/onmt/modules/embeddings.py", line 201, in forward
    source = module(source, step=step)
  File "/Users/USER/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/Users/USER/Desktop/new_version_multi_news/Multi-News/code/OpenNMT-py-baselines/onmt/modules/embeddings.py", line 39, in forward
    emb = emb + self.pe[:emb.size(0)]
RuntimeError: The size of tensor a (9734) must match the size of tensor b (5000) at non-singleton dimension 0
```

**Comment by andysu2008** [comment]
This is my running script:

`python translate.py -gpu -1 -batch_size 50 -beam_size 5 -model  /Users/USER/Desktop/Multi-News/code/OpenNMT-py-baselines/data/newser/OpenNMT-input/newser_step_20000.pt -src /Users/USER/Documents/multi-news/test.txt.src -output /Users/USER/Desktop/Multi-News/code/OpenNMT-py-baselines/data/newser/test-output/test.transformer.out.min_length200 -min_length 200 -max_length 300 -verbose -stepwise_penalty -coverage_penalty summary -beta 5 -length_penalty wu -alpha 0.9 -block_ngram_repeat 3 -ignore_when_blocking "." "</t>" "<t>"
`

**Comment by Alex-Fabbri** [comment]
I did not get that error when running this command on the truncated, and I think it's related to the data you're using. What you are trying to embed is of size 9734 while the max size of self.pe is 5000. You could increase the max_len of the positional embeddings or truncate the data to fix the error.

**Comment by andysu2008** [comment]
@Alex-Fabbri , thanks for your reply. The problem has been resolved. Is it possible for me to ask you one more question? Do you know how to resolve this?

 ```
[2019-11-25 23:27:59,527 INFO] Step 10000/50000; acc:  34.91; ppl: 30.92; xent: 3.43; lr: 0.00088; 2927/1733 tok/s;  47162 sec
[2019-11-25 23:28:01,063 INFO] Loading valid dataset from data/newser/OpenNMT-input/newser.valid.1.pt, number of examples: 3777
 File "train.py", line 118, in <module>
    main(opt)
  File "train.py", line 51, in main
    single_main(opt, 0)
  File "/n/fs/user/Multi-News/code/OpenNMT-py-baselines/onmt/train_single.py", line 136, in main
    opt.valid_steps)
  File "/n/fs/user/Multi-News/code/OpenNMT-py-baselines/onmt/trainer.py", line 196, in train
    valid_stats = self.validate(valid_iter)
  File "/n/fs/user/Multi-News/code/OpenNMT-py-baselines/onmt/trainer.py", line 244, in validate
    batch, outputs, attns)
  File "/n/fs/user/Multi-News/code/OpenNMT-py-baselines/onmt/utils/loss.py", line 107, in monolithic_compute_loss
    _, batch_stats = self._compute_loss(batch, **shard_state)
  File "/n/fs/user/Multi-News/code/OpenNMT-py-baselines/onmt/modules/copy_generator.py", line 190, in _compute_loss
    batch.src_map)
  File "/n/fs/user/miniconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/n/fs/user/Multi-News/code/OpenNMT-py-baselines/onmt/modules/copy_generator.py", line 100, in forward
    out_prob = torch.mul(prob, 1 - p_copy.expand_as(prob))
RuntimeError: CUDA out of memory. Tried to allocate 1.79 GiB (GPU 0; 10.73 GiB total capacity; 6.84 GiB already allocated; 1.15 GiB free; 1.97 GiB cached)
[dsu@head OpenNMT-py-baselines]$ packet_write_wait: Connection to 128.112.155.136 port 22: Broken pipe
```

**Comment by Alex-Fabbri** [comment]
Someone else also ran into an out of memory error at around 10k steps when using the non-truncated data. You could try reducing the batch size and increasing the accum_count to have the same effect while reducing memory usage.

**Comment by andysu2008** [comment]
Hey @Alex-Fabbri 

Thanks so much for your reply. 
Here is the training script:

`
/n/fs/pnlp/dsu/miniconda3/bin/python train.py -save_model models/newser-transformer/newser -data data/newser/OpenNMT-input/newser -copy_attn -word_vec_size 512 -rnn_size 512 -layers 4 -encoder_type transformer -decoder_type transformer -position_encoding -train_steps 50000 -warmup_steps 8000 -learning_rate 2 -decay_method noam -label_smoothing 0.1 -max_grad_norm 0 -dropout 0\.2 -batch_size 4096 -optim adam -adam_beta2 0.998 -param_init 0 -batch_type tokens -normalization tokens -max_generator_batches 2 -accum_count 4 -share_embeddings -param_init_glorot -seed 777 -world_size 1 -gpu_ranks 0 -save_checkpoint_steps 2000
`

Do you know what batch size and accum_count should I use?

**Comment by Alex-Fabbri** [comment]
I see -- strange then that you're getting that OOM error. I am not sure which combination will work -- you probably just need to try and see; starting with batch_size = 2048 and accum_count = 8 sounds reasonable.

**Comment by Alex-Fabbri** [comment]
Going to close this for now -- feel free to re-open and follow up on your findings regarding the batch size and accumulation count.

**Comment by bultiful** [comment]
Hi,andysu. I have a question to ask you: How did you solve the problem? @andysu2008 
RuntimeError: The size of tensor a (5264) must match the size of tensor b (5000) at non-singleton dimension 0
